### ISSUE TITLE
Twitterアカウントを作成する

### ISSUE THREAD

**Issue by fumikito** [musus/frigo#1]
次のアカウントでTwitterを作成する。
- 名前 冷蔵庫
- スクリーン名 なんでもいい

で、アプリケーションセンターにいって、以下の情報を取得する。

https://apps.twitter.com/
- Consumer Key (API Key)
- Consumer Secret (API Secret)
- Access Token
- Access Token Secret

権限はread-write、取得したらSlackで送る。

**Comment by fumikito** [comment]
@musus はやく

**Comment by musus** [comment]
https://twitter.com/myfrigo
